### ISSUE TITLE
Speed of the autocomplete

### ISSUE THREAD

**Issue by brian-provenzano** [evanlucas/fish-kubectl-completions#14]
First off thanks for creating this for fish shell as I have been looking for a good autocomplete for this and kops!  Although still to find for kops...

Anyway, I installed this in my fish shell but am noticing that the autocompletions are fairly slow.  Hitting tab for the completion has a 2-3 second delay vs say this (older, unmaintained fish version https://github.com/danhper/fish-kubectl/blob/master/completions/kubectl.fish ) and the kubectl included bash autocompletions ( kubectl completion bash).  Is there any way to speed it up?

**Comment by evanlucas** [comment]
Hey, thanks for opening the issue. You're absolutely right. In an effort to make the completions more complete, I destroyed the performance of them. I actually had been working on auto generating the completions similar to how the bash and zsh completions are done, but outside of k8s. Can you try the latest commit on the master branch? It should greatly improve the performance of the completions. If not, please let me know.

**Comment by brian-provenzano** [comment]
The latest version does seem to be a lot faster - thanks for the update!  I'll tinker around with it as I use kubectl and let you know if I see any issues.

~~I did notice one thing - "rolling-update" is still around and I believe that command is deprecated or even obsoleted in latest version of kubectl.  But it could be you are keeping it around for those on older versions of kubectl~~
EDIT: forget the above, I see the notation about deprecation in the description of the command :)

Thanks again for doing the work on this!

**Comment by evanlucas** [comment]
Going to go ahead and close this, but feel free to open a new issue with any other questions/problems you may have. Thanks!
