### ISSUE TITLE
Log file in desktop

### ISSUE THREAD

**Issue by jendakol** [evanlucas/fish-kubectl-completions#15]
I have different localization on my Ubuntu laptop then english and https://github.com/evanlucas/fish-kubectl-completions/blob/ca339d153ae3e5823bffd48b3606beb6e3a6dcf4/main.go#L24 fails for me because `Desktop` directory is not named `Desktop`:
```
An error occurred while redirecting file '/home/jenda/Desktop/kubectl.log'                                                                                           
open: No such file or directory
```
You should reflect the localization of the OS. 
However, is it a good idea to put the log on Desktop anyway? :thinking:

**Comment by evanlucas** [comment]
Wow, sorry about that. That shouldn't have been in there :[. Should be fixed on the master branch. Thanks for opening the issue!

**Comment by jendakol** [comment]
Oh, debugging output? I see :smile:  
Thx, nice work
