### ISSUE TITLE
Issue with restricted permissions

### ISSUE THREAD

**Issue by jondavidschober** [evanlucas/fish-kubectl-completions#19]
I tried digging into WHERE the actual issue is but couldn't find it. So I'll describe the issue here.

I am part of an EKS cluster with restricted permissions when I try to auto complete (just about anything) but specifically `kubectl edit deployment <tab>`

I get an error printed out, but the the auto complete is still correct. Not sure what the issue is

     Error from server (Forbidden): customresourcedefinitions.apiextensions.k8s.io is forbidden: User "jschober" cannot list customresourcedefinitions.apiextensions.k8s.io at the cluster scope
     Error from server (Forbidden): customresourcedefinitions.apiextensions.k8s.io is forbidden: User "jschober" cannot list customresourcedefinitions.apiextensions.k8s.io at the cluster scope

**Comment by evanlucas** [comment]
You should be able to `set -Ux FISH_KUBECTL_COMPLETION_COMPLETE_CRDS 0` and then try again with the latest. The issue was that we tried to complete crds, but if you don't have access to list them, then we can't complete them. Please feel free to re-open if the latest doesn't work. Thanks!
