### ISSUE TITLE
Support alias of `kubectl`

### ISSUE THREAD

**Issue by KristianZH** [evanlucas/fish-kubectl-completions#22]
Now a days a lot of users use `k` instead of `kubectl`. Unfortunatelly the auto-completion does not work with `k` notation.

**Comment by evanlucas** [comment]
Ah, that is actually a fish limitation as far as I understand. I use `kc` and it works if you define a function for it like so:

```fish
function kc --wraps kubectl -d 'kubectl shorthand'
  kubectl $argv
end
```

**Comment by aca** [comment]
Fish has 'abbr' which replaces alias. It's feature I love most. You might try it.
```
abbr --global k 'kubectl'
abbr --global ka 'kubectl apply'
abbr --global kd 'kubectl describe'
abbr --global kg 'kubectl get'
```
