### ISSUE TITLE
statfulsets short form 'sts' is missing

### ISSUE THREAD

**Issue by the-redback** [evanlucas/fish-kubectl-completions#8]
Hi,

This a nice and useful tool that I am highly dependent on! B|

Just now I came across a little issue. 
As the title says it all, `statefulsets` short form `sts` is missing in the resources.
Hope you will take a look at it.

**Comment by evanlucas** [comment]
Thanks for the feedback. If you pull the latest version, you should be able to use `sts` as an alias for `statefulsets`. Thanks!
